from __future__ import annotations

from dataclasses import dataclass

@dataclass
class File:
    uid: int # Will be generated by a function
    filename: str # Filename without extension
    extension: str

    def create_obj(cls, raw_filename: str) -> File:
        ...